### PR TITLE
Update submodules and specify master_jammy as remote branch

### PR DESCRIPTION
**Pull request by jackpot51**
I've built this, but would appreciate testing on a non-Pop distribution.

### CODE REVIEW

**Comment by wash2** [comment]
I haven't tested this PR on another distribution yet, but I think it would be good to add cosmic-icons.

**Comment by wiiznokes** [comment]
I've just tested this branch and it seems to works as espected

**Comment by jackpot51** [comment]
I have added cosmic-icons

**Comment by Vixea** [comment]
Arch via the AUR package has been tested too

**Pull request merged**
