### PR TITLE
update-submodules

### PR DESCRIPTION
**Pull request by Vixea**

### CODE REVIEW

**Comment by Vixea** [comment]
I need guidance on what is file path specific in the notification addition because currently it doesn't work on arch probably due to path differences

**Comment by Vixea** [comment]
Looks like the ci failed because of no space left on the device

**Comment by Drakulix** [comment]
> Looks like the ci failed because of no space left on the device

It seems like the addition of cosmic-notifications finally pushed that over the edge.

I am looking at stuff like https://github.com/jlumbroso/free-disk-space/ to work around this problem, because I would really like to keep the script calling `just sysext` and not manually building and cleaning up all the subprojects.

**Comment by Drakulix** [comment]
https://github.com/pop-os/cosmic-epoch/pull/130 seems to do the trick.

Could you rebase on that branch (while still targeting master), then we can see it in action for this CI.
If everything succeeds I will merge both branches in succession.

**Comment by Vixea** [comment]
Could you please provide me the command or a hint on what it is I don't remember what the command is

**Comment by Vixea** [comment]
Also won't be able to until a few hours from now

**Comment by Drakulix** [comment]
> Could you please provide me the command or a hint on what it is I don't remember what the command is

```
git fetch --all
git rebase -i origin/ci_free_space
git push -f
```

should be enough.

**Comment by Vixea** [comment]
should be good to go

**Comment by Drakulix** [comment]
Thanks! Now everything is working fine

**Pull request merged**
