### PR TITLE
chore: bump submodules

### PR DESCRIPTION
**Pull request by jokeyrhyme**
- ran `git submodule foreach --recursive 'git fetch; (git checkout master_jammy || git checkout master); (git pull origin master_jammy || git pull origin master);'`
- confirmed that `just sysext` still works
- confirmed that loading "COSMIC" from my greeter results in a functioning session (editing this PR description from a Firefox window in COSMIC)

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
Well, at least this was caught in CI:

```
/usr/sbin/make -C cosmic-comp all
make: Entering directory '/__w/cosmic-epoch/cosmic-epoch/cosmic-comp'
cargo build --release
    Updating git repository `[https://github.com/smithay//smithay`](https://github.com/smithay//smithay%60)
error: failed to load source for dependency `smithay`

Caused by:
  Unable to update https://github.com/smithay//smithay?rev=25d1176484#25d11764

Caused by:
  object not found - no match for id (25d1176484e1c846c4b510f6a4bf5cc5a6d2e4e9); class=Odb (9); code=NotFound (-3)
make: *** [Makefile:27: all] Error 101
make: Leaving directory '/__w/cosmic-epoch/cosmic-epoch/cosmic-comp'
```

Not sure how I keep "luckily" having the correct commits locally and then having those commits evaporate from the internet after I submit the PR :S

**Comment by jokeyrhyme** [comment]
Well, what's weird is https://github.com/pop-os/cosmic-comp/commit/521d1b149b03833dc6e61c50226f4d72a2f40173 is the commit where `smithay?rev=25d1176484#25d11764` is introduced, but cosmic-epoch is currently pointing at https://github.com/pop-os/cosmic-comp/commit/ea1b976076a3f9c4f21db4f20a5fe3b29aa42f35 which is the commit after that

So, I think it's actually not possible for anyone to build cosmic-comp at the moment, seeing as that commit in smithay is no longer available

Perhaps there was a branch/PR in smithay that was rebased?

**Comment by Drakulix** [comment]
Should be fixed with the latest update to cosmic-comp. Can you update the PR? It should pass CI now and I would gladly merge it.

**Comment by jokeyrhyme** [comment]
- okay, bumped everything again with `git submodule foreach --recursive 'git fetch; (git checkout master_jammy || git checkout master); (git pull origin master_jammy || git pull origin master);'`
- confirmed that `just sysext` works
- typing this comment from Firefox running against the new COSMIC build ( can confirm new window animations, etc, very swish <3 )

**Review by jacobgkau — APPROVED** [review]
CI is now passing. Thank you for the version bump!

**Pull request merged**
