### PR TITLE
Add missing cosmic-text dependency

### PR DESCRIPTION
**Pull request by Yethal**

### CODE REVIEW

**Comment by yochananmarqos** [comment]
It was done with [7ecd86c](https://github.com/pop-os/cosmic-epoch/commit/7ecd86ce28c42b89c98d7c0a130a59024b067398).

**Comment by RyzenDew** [comment]
> It was done with [cd8dc9d](https://github.com/pop-os/cosmic-epoch/commit/cd8dc9d887c74ad8b246cce154f65c1db7112fbd).

no they mean cosmic-text which hasn't been added https://github.com/pop-os/cosmic-text

**Review by RyzenDew — APPROVED** [review]

**Comment by yochananmarqos** [comment]
@RyzenDew [cosmic-text is part of cosmic edit](https://github.com/pop-os/cosmic-edit/blob/master_jammy/Cargo.toml#L31). :wink:

**Comment by RyzenDew** [comment]
> @RyzenDew cosmic-text is [a dependency of cosmic edit](https://github.com/pop-os/cosmic-edit/blob/master_jammy/Cargo.toml#L31). 😉

they need to get better at naming things

**Comment by yochananmarqos** [comment]
@RyzenDew Remember, all this is still in the Alpha stage. Things have changed and may change again before it's ready. They already renamed the text editor from cosmic-text-editor to cosmic-edit. 

Anyway, please close this since it's already implemented.

**Pull request closed without merging**
