### PR TITLE
Add libgbm-dev as a dependency.

### PR DESCRIPTION
**Pull request by edfloreshz**
This dependency was missing from my system and the compositor wasn't building, adding it fixes the problem.

### CODE REVIEW

**Comment by Drakulix** [comment]
Thanks for the interest in the project!
I am having a hard time figuring out, which component might require libsdl2 in our stack and I wonder if instead some dependency of sdl was missing on your system.
Can you attach the error you were getting before installing libsdl2?

**Comment by edfloreshz** [comment]
It appears that the error is no longer present after uninstalling `libsdl2-dev` from my system, my bad, feel free to close this issue.

**Comment by Drakulix** [comment]
That looks like `libgbm` is missing and that is part of mesa, but likely split off into a different package on your system.

**Comment by edfloreshz** [comment]
`libgbm-dev` fixes the issue.

**Comment by Drakulix** [comment]
I don't think I would want to list libgbm as an explicit dependency, given that it is part of mesa.
If the distribution chooses to split mesa into multiple packages (imo a good choice), we should instead list dependencies explicitly for a given distribution likely you proposed in #34.

So I would rather merge #34 and keep the rest of the README as is.

**Comment by edfloreshz** [comment]
Sounds good! And if anybody ever faces this issue hopefully they're be able to find this conversation.

**Pull request closed without merging**
